apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: explorandija
servers: 1
agents: 0
ports:
  - port: 80:80
    nodeFilters:
      - loadbalancer
volumes:
  - volume: ./k3d-volumes:/var/lib/postgresql/data
    nodeFilters:
      - server:0
options:
  k3s:
    extraArgs:
      - arg: --disable=metrics-server
        nodeFilters:
          - server:0
